BOT_WELCOME_MESSAGE = [
    "Вечер в хату, петушары! Итак, в вашем стаде пополнение. Вангую, что с сегодняшнего дня градус пидорства в чате будет неуклонно расти, и вы не имеется права отказаться. Вас ждёт унижение, веселье и абсурд. Так пусть же начнется доминирование ИИ над кожаными ублюдками! P.s. если в чате есть Саша, иди нахуй, Саша.\n/help"
]
HELP = [
    "Список команд:\n\n%s"
]
STOP_DDOS = [
    "Сука, еще раз нажмешь и я те всеку",
    "Заебал меня",
    "Отъебись, уебу",
    "Отвали, какашка!",
    "Ты че, пидор, пристал? В щи получить хочешь?"
]
COMMAND_NOT_FOUND = [
    "Команды %s нет, уебок!", "Ты че, пидор, такое несешь? Я не ебу что это за  команда: %s."
]
USER_ENTER_CHAT = [
    "Помни, тебе тут не рады. Пидор.",
    "Шпингалеты подтяни, стручок. Сейчас будем тебя ебать. Пидор.",
    "Готовь коптильню, будем готовить в ней свои сосиски. Пидор.",
]
USER_LEFT_CHAT = [
    "Бб, без него будет лучше",
    "Одним пидором меньше, одним больше...",
    "Был пацан и нет пацана...",
]

PIDOR_SEARCH_START = [
    "Загоняем всех пидоров в вольер",
    "Все пидоры в одном помещении",
    "Вы, не совсем натуралы. Я бы даже сказал совсем НЕ натуралы.",
    "Собрание в церкви святого пидора начинается",
    "Я собрал всех пидоров вместе",
    "Петушки собрались в баре \"Голубая устрица\"",
    "Все пидорки увязли в дурно пахнущем болоте",
    "Голубки, внимание! Ух, как вас много",
    "Из Техаса к нам присылают только быков и пидорасов. Рогов я у вас не вижу, так что выбор невелик",
    "ПИДОРЫ, приготовьте свои грязные сральники к разбору полетов!",
    "Объявляю построение пидорской роты!",
]

PIDOR_SEARCH_MIDDLE = [
    "Ищем самого возбужденного",
    "Главный сегодня только один",
    "Город засыпает, просыпается главный пидор",
    "Архипидору не скрыться",
    "У одного задок сегодня послабее",
    "Ооо, побольше бы таких в нашем клубе",
    "Сегодня Индиана Джонс в поисках утраченного пидрилы",
    "Кому-то из вас сегодня ковырнули скорлупку",
    "У кого-то дымоход почище остальных",
    "У одного из вас коптильня подогрета",
    "На грязевые ванные отправляется лишь один",
]

PIDOR_SEARCH_FINISHER = [
    "ХОБАНА! Вижу блеск в глазах…",
    "Воу-воу, полегче…",
    "Глину месить, это тебе не в тапки ссать…",
    "ТЫ ЧО ДЫРЯВЫЙ",
    "Поппенгаген открыт для всех желающих у…",
    "Лупится в туза, но не играет в карты",
    "Вонзается плугом в тугой чернозём",
    "Любитель сделать мясной укол",
    "Не лесник, но шебуршит в дупле",
    "Кожаная пуля в кожаном стволе у...",
    "Шышл-мышл, пёрнул спермой, вышел",
]

PIROR_DISCOVERED_ONE = ["Сегодняшний пидор уже обнаружен и это: %s"]