BOT_WELCOME_MESSAGE = ["Welcome to the chatbot! How can I help you today?"]
HELP_MESSAGE = ["I can help you with a variety of things. You can ask me about the weather, news, or even tell me a joke. What would you like to do?"]