version: "3.3"

services:
  unibot:
    container_name: unibot
    networks:
      unibot-net:
    build:
      dockerfile: scripts/Dockerfile
      context: ..
    restart: unless-stopped
    env_file:
      - .env
      - telegram.env
      - discord.env

networks:
  unibot-net:
    name: "unibot-net"
    driver: bridge

