version: "3.3"

services:
  unibot:
    container_name: unibot
    stdin_open: true
    tty: true
    ports:
      - "10100:8080"
    networks:
      unibot-net:
    build:
      dockerfile: scripts/Dockerfile
      context: ..
    restart: unless-stopped
    env_file:
      - .env
      - telegram.env
      - discord.env
    volumes:
      - logs:/var/log/unibot

networks:
  unibot-net:
    name: "unibot-net"
    driver: bridge
